import type { Metadata } from 'next';
import { LegalHeroSection } from '@/components/sections/legal/LegalHeroSection';
import { LegalContentSection } from '@/components/sections/legal/LegalContentSection';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for Nexus Property & Business Services.',
};

const sections = [
  {
    title: '1. Introduction',
    content:
      'Welcome to Nexus Property & Business Services. We are committed to protecting your personal information and your right to privacy. When you visit our website and utilize our on-ground verification services, you trust us with your personal and property-related information.\n\nThis Privacy Policy outlines our strict guidelines regarding the collection, handling, and safeguarding of your data. We take this responsibility seriously to ensure you maintain total confidence while managing your Jamaican assets from abroad.',
  },
  {
    title: '2. Information We Collect',
    content:
      'We collect information that you voluntarily provide to us when you request a service quote, register on the secure Client Portal, or communicate with our team. The personal information that we collect depends on the context of your interactions with us and the Services you request.\n\nPersonal Identifiers: Including your name, email address, phone numbers, and physical mailing address.\n\nProperty-Related Data: Exact coordinates, plot numbers, volume/folio numbers, gate codes, tenant names, and specific instructions necessary to execute visual verifications.\n\nMedia & Documentation: High-resolution photographs, video walk-throughs, drone footage, and visual condition reports generated by our field agents specifically for your portfolio.\n\nFinancial Information: Payment details strictly required to process service fees (processed securely via encrypted third-party payment gateways; we do not store full credit card numbers).',
  },
  {
    title: '3. How We Use Information',
    content:
      'We process your information for purposes based on legitimate business interests, the fulfillment of our service contracts with you, compliance with our legal obligations, and your consent.\n\nTo Provide Verification Services: Dispatching agents to the correct coordinates and ensuring accurate site-specific reporting.\n\nTo Generate Reports: Compiling raw data, images, and visual observations into standardized, secure PDF verification audits.\n\nTo Communicate with Clients: Sending real-time updates, confirmation notices, delivery links, and responding to direct inquiries or support requests.\n\nAdministrative Purposes: Managing accounts, processing payments, and maintaining secure access to the Client Portal.',
  },
  {
    title: '4. Data Protection',
    content:
      'We implement a variety of security measures to maintain the safety of your personal information when you place a service request or enter, submit, or access your personal information.\n\nAll sensitive information you supply is encrypted via Secure Socket Layer (SSL) technology and stored in encrypted databases. Access to your data is strictly limited to authorized personnel only, and multi-factor authentication is enforced on all administrative systems.',
  },
  {
    title: '5. Sharing of Information',
    content:
      'We do not sell, trade, or otherwise transfer your personally identifiable information to outside parties without your explicit consent, except as required by law or to protect our rights.\n\nWe may share information with trusted third-party service providers who assist us in operating our website, processing payments, or conducting our business, provided they agree to keep this information confidential.',
  },
  {
    title: '6. Client Portal Security',
    content:
      'Your client portal account is protected by encrypted login credentials. You are responsible for maintaining the confidentiality of your account details. We employ industry-standard security protocols including end-to-end encryption for all document transfers and communications through the portal.',
  },
  {
    title: '7. Data Retention',
    content:
      'We retain your personal information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law. Upon termination of our service agreement, we will securely delete or anonymize your data within 90 days, except where retention is required for legal compliance.',
  },
  {
    title: '8. Your Rights',
    content:
      'You have the right to access, update, or delete your personal information at any time. You may request a copy of the data we hold about you, object to processing activities, or request data portability where applicable.\n\nTo exercise these rights, please contact us directly. We will respond to your request within 30 days in accordance with applicable data protection regulations.',
  },
  {
    title: '9. Contact Information',
    content:
      'For questions, concerns, or data-related requests, please contact us:\n\nEmail: info@nexuspbs.net\nPhone: (561) 639-8772\nOffice Hours: Mon-Fri, 9:00 AM - 5:00 PM\n\nWe are committed to resolving any privacy concerns promptly and transparently.',
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <LegalHeroSection
        title="Privacy Policy"
        description="Your privacy and data security are important to us. This policy explains how we collect, use, and protect your information across our verification services."
        date="July 13, 2026"
      />
      <LegalContentSection sections={sections} />
    </>
  );
}
